# Generated by Django 5.2.14 on 2026-06-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceattempt',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
