# Generated by Django 5.2.14 on 2026-06-25 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practiceattempt_highlights_practiceattempt_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('html_content', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='article_audio/')),
                ('vocabulary', models.JSONField(blank=True, default=dict)),
                ('allow_highlighting', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DictationExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('audio_file', models.FileField(upload_to='dictation_audio/')),
                ('transcript', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dictations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DictationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_text', models.TextField(blank=True)),
                ('accuracy_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.dictationexercise')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('skill', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking'), ('article', 'Article'), ('dictation', 'Dictation'), ('podcast', 'Podcast')], max_length=20)),
                ('section_type', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3'), ('part4', 'Part 4'), ('passage1', 'Passage 1'), ('passage2', 'Passage 2'), ('passage3', 'Passage 3'), ('task1', 'Task 1'), ('task2', 'Task 2'), ('full', 'Full')], max_length=20)),
                ('html_content', models.TextField(help_text='Trusted teacher HTML. It renders with {{ test.html_content|safe }} in the test runner.')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='test_audio/')),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('allow_highlighting', models.BooleanField(default=True)),
                ('auto_play_audio', models.BooleanField(default=False)),
                ('mobile_optimized', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['skill', 'section_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FullMockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mock_tests', to=settings.AUTH_USER_MODEL)),
                ('listening_test', models.ForeignKey(limit_choices_to={'skill': 'listening'}, on_delete=django.db.models.deletion.PROTECT, related_name='mock_listening_sections', to='practice.test')),
                ('reading_test', models.ForeignKey(limit_choices_to={'skill': 'reading'}, on_delete=django.db.models.deletion.PROTECT, related_name='mock_reading_sections', to='practice.test')),
                ('writing_test', models.ForeignKey(limit_choices_to={'skill': 'writing'}, on_delete=django.db.models.deletion.PROTECT, related_name='mock_writing_sections', to='practice.test')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('mistakes', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('color', models.CharField(default='yellow', max_length=24)),
                ('client_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='practice.testattempt')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['skill', 'section_type', 'is_published'], name='practice_te_skill_5c088a_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['slug'], name='practice_te_slug_de9b14_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'test', 'is_submitted'], name='practice_te_user_id_ff45cc_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['is_locked'], name='practice_te_is_lock_050e59_idx'),
        ),
    ]
